Comment "Fireface UCX II"

# The Fireface UCX II provides 20 playback and capture channels each:
# - channels  0  to  7 are analog inputs and outputs
# - channels  8 and  9 are S/PDIF via coax
# - channels 10 and 11 are AES/EBU or S/PDIF via XLR
# - channels 12  to 19 are ADAT (8 channels) or S/PDIF (12 and 13) via TOSLINK
#
#
# Physical connector layout:
#
# Front:
# - 1 MIC / LINE: XLR / 1/4" combo, balanced mono input, 48 V phantom power
# - 2 MIC / LINE: XLR / 1/4" combo, balanced mono input, 48 V phantom power
# - 3 LINE / INSTR.: TRS 1/4", balanced mono input
# - 4 LINE / INSTR.: TRS 1/4", balanced mono input
# - Headphones symbol: TRS 1/4", unbalanced stereo output
#
# Back:
# - LINE INPUTS (BALANCED) [5, 6; 7, 8]: TRS 1/4", balanced mono outputs
# - LINE OUTPUTS (BALANCED) [1, 2; 3, 4; 5, 6]: TRS 1/4", balanced mono outputs
# - ADAT IN: TOSLINK
# - ADAT OUT: TOSLINK
# - AES/EBU & SPDIF: 9-pin D-Sub with breakout cable (2 RCA and 2 XLR)

SectionUseCase."HiFi" {
	Comment "Default"
	File "/USB-Audio/RME/Fireface-UCX-II-HiFi.conf"
}

Define.DirectPlaybackChannels 20
Define.DirectCaptureChannels 20

Include.dhw.File "/common/direct.conf"
